extends RefCounted

const GearProfiles = preload("res://game_data/item_gear_profiles.gd")

## Canonical item metadata. This is a detached authored source;
## actions, slots, markets and condition fields are metadata until their
## gameplay authorities are implemented by later slices.
static func rows() -> Array:
	return [
		_row("old_revolver", "舊式左輪", "WEAPON", "revolver", 1000, 160, false, 1, ["main_hand"], ["shoot"], ["firearm", "revolver"], ["new_hope"], ["guard_stock"], {"new_hope": "low", "gray_valley": "none", "dry_well": "none"}, {"new_hope": "medium", "gray_valley": "medium", "dry_well": "medium"}, "新希望護衛隊整理的舊槍。裝備後可射擊，每次消耗一發左輪彈藥；傷害為 6 加槍械等級。", "item_old_revolver"),
		_row("revolver_round", "左輪彈藥", "CONSUMABLE", "cartridge", 20, 12, true, 100, [], ["fire"], ["ammunition"], ["new_hope"], ["guard_stock"], {"new_hope": "high", "gray_valley": "none", "dry_well": "none"}, {"new_hope": "medium", "gray_valley": "low", "dry_well": "medium"}, "供舊式左輪使用的一發彈藥。每次有效射擊消耗一發；沒有彈藥仍可近身攻擊或撤退。", "item_revolver_round"),
		_row("rusted_knife", "生鏽小刀", "WEAPON", "utility_blade", 250, 18, false, 1, ["main_hand"], ["cut_rope", "scrape_label", "defend"], ["blade", "tool", "corroded"], ["settlement_households", "abandoned_homes"], ["kitchen_drawer", "discarded_travel_kit"], {"new_hope": "high", "gray_valley": "high", "dry_well": "medium"}, {"new_hope": "medium", "gray_valley": "low", "dry_well": "medium"}, "刀尖早已缺了一角，木柄刻著一排難以辨認的姓氏。", "item_rusted_knife"),
		_row("hunting_knife", "獵刀", "WEAPON", "hunting_blade", 400, 72, false, 1, ["main_hand"], ["dress_game", "cut_brush", "inspect_hide"], ["blade", "hunting", "sheath"], ["new_hope", "hunters"], ["hunting_lodge", "hunter_tool_roll"], {"new_hope": "medium", "gray_valley": "low", "dry_well": "low"}, {"new_hope": "high", "gray_valley": "medium", "dry_well": "medium"}, "磨薄的刃口旁留著深色水痕，皮鞘反覆補過線。", "item_hunting_knife"),
		_row("rebar_club", "鋼筋棍", "WEAPON", "improvised_club", 1800, 22, false, 1, ["main_hand"], ["brace_panel", "drive_stake", "defend"], ["blunt", "rebar", "improvised"], ["gray_valley", "construction_ruins"], ["collapsed_slab", "salvage_heap"], {"new_hope": "medium", "gray_valley": "high", "dry_well": "low"}, {"new_hope": "low", "gray_valley": "low", "dry_well": "medium"}, "一截混凝土鋼筋，握端留下被敲平的切口。", "item_rebar_club"),
		_row("scrap_machete", "廢鐵砍刀", "WEAPON", "salvage_machete", 1200, 48, false, 1, ["main_hand"], ["clear_brush", "cut_binding"], ["blade", "brush_cutting", "salvage_made"], ["gray_valley", "local_smiths"], ["smith_workbench", "scavenger_pack"], {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, {"new_hope": "high", "gray_valley": "medium", "dry_well": "low"}, "刀背保留著原鋼板的折線，刃口卻磨得整齊。", "item_scrap_machete"),
		_row("work_clothes", "舊工作服", "APPAREL", "workwear", 1200, 28, false, 1, ["body"], ["wear_workwear", "inspect_name_patch"], ["cloth", "workwear", "pockets"], ["gray_valley", "settlements"], ["worker_locker", "secondhand_clothing_stall"], {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "low"}, "袖口補丁壓著補丁，胸前名牌只剩一個姓。", "item_work_clothes"),
		_row("desert_robe", "沙地長袍", "APPAREL", "desert_wrap", 900, 55, false, 1, ["body"], ["wrap_against_dust", "shade_supplies"], ["cloth", "desert", "loose_layers"], ["dry_well", "desert_households"], ["desert_clothing_stall", "caravan_spare_bundle"], {"new_hope": "low", "gray_valley": "medium", "dry_well": "high"}, {"new_hope": "low", "gray_valley": "medium", "dry_well": "high"}, "寬鬆布層在腰間束起，褪色邊緣補著另一種織法。", "item_desert_robe"),
		_row("caravan_coat", "商隊外套", "APPAREL", "travel_coat", 1500, 85, false, 1, ["body"], ["wear_travel_coat", "inspect_route_patch"], ["coat", "caravan", "reinforced"], ["caravan_tailors", "route_settlements"], ["caravan_lost_property", "travelling_tailor"], {"new_hope": "medium", "gray_valley": "medium", "dry_well": "medium"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "high"}, "肩頭的舊路線章被拆掉，只留下較淺的一圈布色。", "item_caravan_coat"),
		_row("travel_backpack", "舊旅行包", "CONTAINER", "travel_pack", 1100, 60, false, 1, ["back"], ["pack_trip_supplies", "inspect_straps"], ["backpack", "cloth", "repaired"], ["settlement_tailors", "caravan_routes"], ["secondhand_pack_stall", "traveller_storage"], {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, {"new_hope": "high", "gray_valley": "high", "dry_well": "high"}, "兩條肩帶磨成不同顏色，背面縫著三層補丁。", "item_travel_backpack"),
		_row("military_backpack", "軍用背包", "CONTAINER", "field_supply_pack", 2400, 220, false, 1, ["back"], ["pack_trip_supplies", "inspect_unit_marks"], ["backpack", "military", "salvaged"], ["old_world_depots"], ["sealed_field_kit", "wilderness_wreck"], {"new_hope": "none", "gray_valley": "none", "dry_well": "none"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "high"}, "多個外袋的扣件不盡相同，內側有褪色的點收印。", "item_military_backpack"),
		_row("old_world_saber", "舊世軍刀", "WEAPON", "military_sabre", 1300, 300, false, 1, ["main_hand"], ["inspect_unit_marks", "defend"], ["blade", "military", "old_world"], ["old_world_depots"], ["old_armory"], {"new_hope": "none", "gray_valley": "none", "dry_well": "none"}, {"new_hope": "high", "gray_valley": "high", "dry_well": "high"}, "刀身比鎮上任何一把都直，護手上刻著早已不存在的部隊番號。", "item_old_world_saber"),
		_row("rope", "繩索", "TOOL", "utility_rope", 2500, 30, false, 1, [], ["secure_cargo", "lower_bundle", "anchor_line"], ["rope", "travel"], ["caravan", "settlement_workshop"], ["cargo_store", "bridge_maintenance_box"], {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, {"new_hope": "medium", "gray_valley": "medium", "dry_well": "high"}, "粗繩盤成一圈，繩端包著便於辨認的布條。", "item_rope"),
		_row("flashlight", "手電筒", "TOOL", "handheld_light", 400, 35, false, 1, [], ["illuminate", "signal", "inspect"], ["lighting", "electric"], ["gray_valley", "old_world_home"], ["maintenance_box", "household_drawer"], {"new_hope": "medium", "gray_valley": "high", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "high"}, "磨花的燈罩旁刻著前任使用者的值班號碼。", "item_flashlight"),
		_row("wrench", "扳手", "TOOL", "adjustable_wrench", 700, 25, false, 1, [], ["turn_fastener", "hold_joint", "lend"], ["hand_tool", "metal"], ["gray_valley", "industrial_ruin"], ["maintenance_box", "pump_shed"], {"new_hope": "medium", "gray_valley": "high", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "medium", "dry_well": "high"}, "可調開口的扳手，握柄沾著擦不掉的機油。", "item_wrench"),
		_row("first_aid_kit", "急救包", "CONSUMABLE", "field_medical_kit", 800, 55, true, 20, [], ["offer_field_aid", "donate", "check_contents"], ["medical"], ["settlement_clinic", "caravan"], ["emergency_cabinet", "caravan_medical_bag"], {"new_hope": "medium", "gray_valley": "medium", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "high"}, "耐磨小包以分格收好未拆封的急救耗材。", "item_first_aid_kit"),
		_row("sledgehammer", "鐵鎚", "WEAPON", "sledgehammer", 3200, 38, false, 1, ["main_hand"], ["defend"], ["blunt", "heavy"], ["gray_valley"], ["workshop"], {"new_hope": "low", "gray_valley": "medium", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "low", "dry_well": "medium"}, "普通民用鐵鎚。近戰傷害 6 加近戰等級；重 3.2 公斤，撤退承受 2 傷害。", "item_sledgehammer"),
		_row("combat_knife", "戰鬥刀", "WEAPON", "combat_blade", 450, 90, false, 1, ["main_hand"], ["defend"], ["blade", "military"], ["new_hope"], ["guard_stock"], {"new_hope": "medium", "gray_valley": "low", "dry_well": "none"}, {"new_hope": "medium", "gray_valley": "low", "dry_well": "medium"}, "輕巧的專業戰鬥刀。近戰傷害 4 加近戰等級，僅重 0.45 公斤，留出携帶工具的空間。", "item_combat_knife"),
		_row("reinforced_saber", "強化軍刀", "WEAPON", "reinforced_sabre", 1600, 200, false, 1, ["main_hand"], ["defend"], ["blade", "reinforced"], ["new_hope"], ["guard_stock"], {"new_hope": "low", "gray_valley": "none", "dry_well": "none"}, {"new_hope": "medium", "gray_valley": "low", "dry_well": "medium"}, "軍用強化刃。近戰傷害 6 加近戰等級，比鐵鎚輕，撤退仍只承受 1 傷害。", "item_reinforced_saber"),
		_row("police_revolver", "警用左輪", "WEAPON", "police_revolver", 1200, 230, false, 1, ["main_hand"], ["shoot"], ["firearm", "revolver"], ["new_hope"], ["guard_stock"], {"new_hope": "low", "gray_valley": "none", "dry_well": "none"}, {"new_hope": "medium", "gray_valley": "low", "dry_well": "medium"}, "專業制式左輪。射擊傷害 7 加槍械等級，沿用左輪彈藥，每次消耗 1 發。", "item_police_revolver"),
		_row("short_shotgun", "短管霰彈槍", "WEAPON", "short_shotgun", 2800, 240, false, 1, ["main_hand"], ["shoot"], ["firearm", "shotgun"], ["new_hope"], ["guard_stock"], {"new_hope": "low", "gray_valley": "none", "dry_well": "none"}, {"new_hope": "medium", "gray_valley": "low", "dry_well": "medium"}, "短管近距離槍械。射擊傷害 10 加槍械等級；每次消耗 1 發霰彈，彈藥比左輪貴。", "item_short_shotgun"),
		_row("shotgun_shell", "霰彈槍彈藥", "CONSUMABLE", "shotgun_shell", 50, 30, true, 100, [], ["fire"], ["ammunition"], ["new_hope"], ["guard_stock"], {"new_hope": "high", "gray_valley": "none", "dry_well": "none"}, {"new_hope": "medium", "gray_valley": "low", "dry_well": "medium"}, "供短管霰彈槍使用的一發彈藥。每次有效射擊消耗 1 發，傷害高，補充成本也高。", "item_shotgun_shell"),
		_row("thick_cloth_coat", "厚布外套", "APPAREL", "cloth_coat", 900, 35, false, 1, ["body"], ["wear_armor"], ["cloth"], ["settlement_workshop"], ["workshop"], {"new_hope": "medium", "gray_valley": "medium", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "防護 0，輕便的厚布外套。", "item_thick_cloth_coat"),
		_row("leather_jacket", "皮革夾克", "APPAREL", "leather_armor", 1400, 80, false, 1, ["body"], ["wear_armor"], ["leather"], ["settlement_workshop"], ["workshop"], {"new_hope": "medium", "gray_valley": "medium", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "防護 1，每次敵方反擊減傷 1。", "item_leather_jacket"),
		_row("reinforced_leather_jacket", "強化皮甲", "APPAREL", "reinforced_armor", 1900, 160, false, 1, ["body"], ["wear_armor"], ["leather", "reinforced"], ["settlement_workshop"], ["workshop"], {"new_hope": "medium", "gray_valley": "medium", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "防護 2，每次敵方反擊減傷 2。", "item_reinforced_leather_jacket"),
		_row("ballistic_vest", "防彈背心", "APPAREL", "ballistic_armor", 3000, 240, false, 1, ["body"], ["wear_armor"], ["military", "heavy"], ["settlement_workshop"], ["workshop"], {"new_hope": "low", "gray_valley": "low", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "防護 3；生存物資容量 −3；不能潛行繞過路障。", "item_ballistic_vest"),
		_row("reinforced_travel_backpack", "強化旅行包", "CONTAINER", "reinforced_pack", 1800, 130, false, 1, ["back"], ["pack_trip_supplies"], ["backpack", "reinforced"], ["settlement_workshop"], ["workshop"], {"new_hope": "medium", "gray_valley": "medium", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "生存物資容量 +10，路戰敗退最多損失 1 水。", "item_reinforced_travel_backpack"),
		_row("repair_toolbox", "修理工具箱", "TOOL", "mechanical_tools", 2200, 95, false, 1, [], ["repair"], ["hand_tool"], ["settlement_workshop"], ["workshop"], {"new_hope": "medium", "gray_valley": "medium", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "機械實體工具 2；需機械 2 才能拆開軍械庫。", "item_repair_toolbox"),
		_row("precision_repair_kit", "精密修理組", "TOOL", "precision_tools", 1800, 260, false, 1, [], ["repair"], ["hand_tool", "precision"], ["settlement_workshop"], ["workshop"], {"new_hope": "low", "gray_valley": "low", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "機械實體工具 3；需機械 3 才能精修井泵，產水 +2。", "item_precision_repair_kit"),
		_row("simple_meter", "簡易電錶", "TOOL", "electronic_tools", 500, 45, false, 1, [], ["repair"], ["electric"], ["settlement_workshop"], ["workshop"], {"new_hope": "medium", "gray_valley": "medium", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "電子實體工具 1；搭接軍械庫需電子 2 和 2 廢料。", "item_simple_meter"),
		_row("electronic_repair_kit", "電子修理組", "TOOL", "electronic_tools", 1700, 130, false, 1, [], ["repair"], ["electric"], ["settlement_workshop"], ["workshop"], {"new_hope": "medium", "gray_valley": "medium", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "電子實體工具 2；需電子 2 才能重接井泵線路。", "item_electronic_repair_kit"),
		_row("military_electronic_tools", "軍用電子工具", "TOOL", "military_electronic_tools", 2500, 280, false, 1, [], ["repair"], ["electric", "military"], ["settlement_workshop"], ["workshop"], {"new_hope": "low", "gray_valley": "low", "dry_well": "low"}, {"new_hope": "medium", "gray_valley": "high", "dry_well": "medium"}, "電子實體工具 3；需電子 3 才能校準軍械庫，免耗廢料。", "item_military_electronic_tools"),
	]

static func _row(id: String, label: String, category: String, subtype: String, weight: int, value: int, stackable: bool, max_stack: int, slots: Array, actions: Array, tags: Array, origins: Array, loot: Array, supply: Dictionary, demand: Dictionary, description: String, asset: String) -> Dictionary:
	var row := {
		"item_id": id, "display_name_zh": label, "category": category, "subtype": subtype,
		"base_weight": weight, "base_value": value, "stackable": stackable, "max_stack": max_stack,
		"condition": null, "max_condition": null, "equip_slots": slots, "actions": actions,
		"tags": tags, "origin_tags": origins, "loot_sources": loot,
		"settlement_supply": supply, "settlement_demand": demand,
		"description_zh": description, "asset_id": asset
	}
	row.merge(GearProfiles.resolve(id))
	return row
