"""Copy original generated bytes and record metadata; never edit bitmap pixels."""
import argparse
import hashlib
import json
import shutil
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--group", required=True, choices=["weapons", "clothing", "supplies", "relics"])
    parser.add_argument("--id", required=True)
    parser.add_argument("--source", required=True)
    args = parser.parse_args()
    folder = ROOT / "ui/assets/items/library" / args.group
    jobs = json.loads((folder / "prompts.json").read_text(encoding="utf-8-sig"))["jobs"]
    job = next(job for job in jobs if job["id"] == args.id)
    assert args.id.replace("_", "").isalnum(), "Invalid asset identifier"
    source = Path(args.source).resolve(strict=True)
    destination = folder / (args.id + ".png")
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    if destination.exists():
        assert hashlib.sha256(destination.read_bytes()).hexdigest() == digest, "Refusing different-byte overwrite"
    else:
        shutil.copyfile(source, destination)
    assert hashlib.sha256(destination.read_bytes()).hexdigest() == digest
    with Image.open(destination) as bitmap:
        bitmap.load()
        assert bitmap.mode == "RGBA", "Output needs genuine RGBA transparency"
        alpha = bitmap.getchannel("A")
        assert alpha.getextrema() == (0, 255), "Output needs transparent and opaque pixels"
        assert min(bitmap.size) >= 512 and alpha.getbbox(), "Empty or undersized bitmap"
        record = {
            "id": args.id, "name": job["name"], "section": job["section"],
            "art_role": job.get("art_role", "item_illustration"),
            "file": destination.relative_to(ROOT).as_posix(),
            "source_output": source.name, "sha256": digest,
            "size": list(bitmap.size), "mode": bitmap.mode,
            "alpha_bounds": list(alpha.getbbox()), "alpha_range": [0, 255],
            "generator": "built-in image_gen", "art_status": "GENERATED",
            "gameplay_status": "NOT_IMPLEMENTED",
        }
    records = folder / "records"
    records.mkdir(exist_ok=True)
    (records / (args.id + ".json")).write_text(json.dumps(record, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"PASS: {args.group}/{args.id}; original PNG copied and transparency verified.")


if __name__ == "__main__":
    main()
